<?php

/**
 * @file
 * Enables Drupal to send e-mail directly to an SMTP server.
 *
 * This module uses a customized extract of the PHPMailer
 * library (originally by Brent R. Matzelle, now maintained
 *  by Codeworx Tech.) relicensed from LGPL to GPL, included
 * as a part of the module.
 *
 * Overriding mail handling in Drupal to make SMTP the default
 * transport layer, requires to change the 'system.mail.interface'
 * default value array('default' => 'Drupal\Core\Mail\PhpMail').
 * This module uses array('default' => 'SMTPMailSystem').
 */

/**
 * Implements hook_help().
 */
function smtp_help($path, $arg) {
  switch ($path) {
    case 'admin/help#smtp':
      return t('Allow for site emails to be sent through an SMTP server of your choice.');
  }
}

/**
 * Implements hook_menu().
 */
function smtp_menu() {
  $items['admin/config/system/smtp'] = array(
    'title' => 'SMTP Authentication Support',
    'description' => 'Allow for site emails to be sent through an SMTP server of your choice.',
    'route_name' => 'smtp.config',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function smtp_permission() {
  return array(
    'administer smtp module' => array(
      'title' => t('Administer SMTP Authentication Support module'),
      'description' => t('Perform administration tasks for SMTP Authentication Support module.')
    ),
  );
}


/**
 * Implements hook_mail().
 */
function smtp_mail($key, &$message, $params) {
  if ($key == 'smtp-test') {
    $message['subject'] = $params['subject'];
    $message['body'] = $params['body'];
  }
}

/**
 * smtp_send_queue queuer.
 */
function smtp_send_queue($mailerObj) {
  $queue = Drupal::queue('smtp_send_queue');
  $queue->createItem($mailerObj);
}

function _smtp_mailer_send($variables) {
  $nr_mails_sent = &drupal_static(__FUNCTION__, 0);

  $logger = \Drupal::logger('smtp');
  $smtp_config = \Drupal::config('smtp.settings');
  $batch_size = $smtp_config->get('smtp_batch_size');
  // A $batch_size of 0 means unlimited, so we will check if we reached the
  // limit only if we actually have a value in it.
  if (!empty($batch_size) && $nr_mails_sent >= $batch_size) {
    // If we reached the limit, we reset it and wait for one second.
    $nr_mails_sent = 0;
    $logger->info('The batch size limit has been reached, waiting for one second...');
    sleep(1);
  }
  $nr_mails_sent++;
  $mailer = $variables['mailer'];
  $to = $variables['to'];
  $from = $variables['from'];

  // Let the people know what is going on.
  $logger->info('Sending mail to: @to', array('@to' => $to));

  // Try to send e-mail. If it fails, set watchdog entry.
  if (!$mailer->Send()) {
    $logger->error('Error sending e-mail from @from to @to : !error_message', array('@from' => $from, '@to' => $to, '!error_message' => $mailer->ErrorInfo));
    return FALSE;
  }

  $mailer->SmtpClose();
  return TRUE;
}
